apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: ${{ secrets.DOCKERHUB_USERNAME }}/mlops_project:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/weather_app"  # Connecting to MongoDB service

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: NodePort  # Exposes the service externally
  selector:
    app: flask-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005  # Accessible from external nodes on this port