name: CI Pipeline

on:
  push:
    branches:
      - testing  # Trigger this pipeline when code is pushed to the testing branch

jobs:
  test:
    runs-on: ubuntu-latest
    

    strategy:
      matrix:
        mongodb-version: ['6.0', '7.0', '8.0']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r App/requirements.txt

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Run unit tests
      run: |
        pytest App/test.py  # assuming your test files are in the 'tests' directory

  docker_build_push:
    runs-on: ubuntu-latest
    needs: test  # Run after the 'test' job completes

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mlops_project:latest

    # - name: Build Docker image
    #   run: |
    #     docker build -t myapp:latest .

    # - name: Push Docker image
    #   run: |
    #     docker tag myapp:latest syedaareeba/mlops_project:latest
    #     docker push syedaareeba/mlops_project:latest
